---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# ccwarcs    
  
<!-- badges: start -->
<!-- badges: end -->

Provides access to Common Crawl WARC files via Amazon Web Services.

## Installation

 <!-- You can install the released version of ccwarcs from [CRAN](https://CRAN.R-project.org) with: -->
<!-- ``` r -->
<!-- install.packages("ccwarcs") -->
<!-- ``` -->

You can install the development version of ccwarcs from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jasonmtroos/ccwarcs")
```

```{r child = "vignettes/introduction-to-ccwarcs.Rmd"}
```

## Contributing

Please note that the 'ccwarcs' project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md).
By contributing to this project, you agree to abide by its terms.


